### ISSUE TITLE
將一半DDR預留給NOOP

### ISSUE THREAD

**Issue by sashimi-yzh** [NJUCS-ComputerSystemLab-2017/NPC#2]
修改zynq的devicetree, 將zynq linux看到的memory縮小一半, 另一半留給NOOP.

**Comment by sashimi-yzh** [comment]
linux內核有dts

http://lxr.free-electrons.com/source/arch/arm/boot/dts/zynq-zed.dts

**Comment by njucjc** [comment]
将sd卡中的devicetree_ramdisk.dtb反编译为dts，然后修改其内容，最后编译替换原有的dtb
$ sudo apt-get install device-tree-compiler
$dtc -I dtb -O dts -o tree.dts devicetree_ramdisk.dtb
$vim tree.dts //将memory的size该为原来的一半
$dtc -I dts -O dtb -o devicetree_ramdisk.dtb tree.dts 
替换原有dtb即可

**Comment by sashimi-yzh** [comment]
已完成, 啟動后看到linux的可用內存減小了一半.
